# Generated by Django 6.0.4 on 2026-04-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order_index', models.PositiveIntegerField()),
                ('exercise_type', models.CharField(choices=[('numerical', 'Numerical'), ('document_upload', 'Document upload')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.tutorial')),
            ],
            options={
                'ordering': ['tutorial_id', 'order_index', 'id'],
                'constraints': [models.UniqueConstraint(fields=('tutorial', 'order_index'), name='core_exercise_unique_order_per_tutorial')],
            },
        ),
    ]
