# Generated by Django 6.0.4 on 2026-04-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_text', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='exercise_variants/images/')),
                ('reference_solution', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('absolute_tolerance', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('available_points', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('supervisor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.exercise')),
            ],
            options={
                'ordering': ['exercise_id', 'id'],
            },
        ),
    ]
