# Generated by Django 6.0.4 on 2026-04-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exercisevariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisevariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_variants/images/'),
        ),
    ]
