# Generated by Django 6.0.4 on 2026-05-04 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_result_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='courses_supervised', to=settings.AUTH_USER_MODEL),
        ),
    ]
