# Generated by Django 6.0.4 on 2026-05-05 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_supervisors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='result',
            name='core_result_unique_active_student_exercise',
        ),
        migrations.AddField(
            model_name='archivebatch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_batches', to='core.course'),
        ),
        migrations.AddField(
            model_name='archivebatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_batches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='archive_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='core.archivebatch'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(condition=models.Q(('archive_batch__isnull', True)), fields=('student', 'exercise'), name='core_result_unique_active_student_exercise'),
        ),
    ]
