# Generated by Django 6.0.4 on 2026-05-05 15:15

from decimal import Decimal

import core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_parts_and_result_parts(apps, schema_editor):
    ExercisePart = apps.get_model("core", "ExercisePart")
    ExerciseVariant = apps.get_model("core", "ExerciseVariant")
    Result = apps.get_model("core", "Result")
    ResultPart = apps.get_model("core", "ResultPart")

    part_ids_by_variant_id = {}
    variants = ExerciseVariant.objects.select_related("exercise").all().order_by("id")
    for variant in variants:
        label = "a"
        answer_type = (
            "document_upload"
            if variant.exercise.exercise_type == "document_upload"
            else "numerical"
        )
        part = ExercisePart.objects.create(
            variant=variant,
            label=label,
            prompt_text="",
            answer_type=answer_type,
            reference_solution=variant.reference_solution,
            absolute_tolerance=variant.absolute_tolerance,
            available_points=variant.available_points,
            order_index=1,
        )
        part_ids_by_variant_id[variant.id] = part.id

    results = Result.objects.select_related("assigned_variant").all().order_by("id")
    for result in results:
        variant_id = result.assigned_variant_id
        if not variant_id:
            continue
        part_id = part_ids_by_variant_id.get(variant_id)
        if not part_id:
            continue
        ResultPart.objects.create(
            result=result,
            exercise_part_id=part_id,
            submitted_numerical_value=result.submitted_numerical_value,
            uploaded_file=result.uploaded_file,
            is_correct=result.is_correct,
            score=result.score if result.score is not None else Decimal("0"),
        )


def reverse_backfill_parts_and_result_parts(apps, schema_editor):
    # Schema rollback drops these tables; no reverse data transform needed.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_archivebatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('prompt_text', models.TextField(blank=True)),
                ('answer_type', models.CharField(choices=[('numerical', 'Numerical'), ('document_upload', 'Document upload')], default='numerical', max_length=20)),
                ('reference_solution', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('absolute_tolerance', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('available_points', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.exercisevariant')),
            ],
            options={
                'ordering': ['variant_id', 'order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResultPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_numerical_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='student_submissions/', validators=[core.validators.validate_student_submission_file])),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_parts', to='core.exercisepart')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.result')),
            ],
            options={
                'ordering': ['result_id', 'exercise_part__order_index', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='exercisepart',
            constraint=models.UniqueConstraint(fields=('variant', 'label'), name='core_exercisepart_unique_label_per_variant'),
        ),
        migrations.AddConstraint(
            model_name='exercisepart',
            constraint=models.UniqueConstraint(fields=('variant', 'order_index'), name='core_exercisepart_unique_order_per_variant'),
        ),
        migrations.AddConstraint(
            model_name='resultpart',
            constraint=models.UniqueConstraint(fields=('result', 'exercise_part'), name='core_resultpart_unique_result_exercisepart'),
        ),
        migrations.RunPython(backfill_parts_and_result_parts, reverse_backfill_parts_and_result_parts),
    ]
