# Generated by Django 6.0.4 on 2026-05-06 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_exercisepart_resultpart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisevariant',
            name='absolute_tolerance',
        ),
        migrations.RemoveField(
            model_name='exercisevariant',
            name='available_points',
        ),
        migrations.RemoveField(
            model_name='exercisevariant',
            name='reference_solution',
        ),
        migrations.RemoveField(
            model_name='result',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='result',
            name='graded_at',
        ),
        migrations.RemoveField(
            model_name='result',
            name='graded_by',
        ),
        migrations.RemoveField(
            model_name='result',
            name='is_manually_graded',
        ),
        migrations.RemoveField(
            model_name='result',
            name='submitted_numerical_value',
        ),
        migrations.RemoveField(
            model_name='result',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='resultpart',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resultpart',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultpart',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_result_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultpart',
            name='is_manually_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultpart',
            name='reference_value_used',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='resultpart',
            name='tolerance_used',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
