# Generated by Django 6.0.4 on 2026-05-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_exercise_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisepart',
            name='absolute_tolerance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercisepart',
            name='reference_solution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultpart',
            name='reference_value_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultpart',
            name='submitted_numerical_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultpart',
            name='tolerance_used',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
