from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    CourseDetailView,
    CourseListView,
    ExerciseDetailView,
    LogoutView,
    RegisterView,
    RoleAwareLoginView,
    SupervisorArchivedSubmissionFileDownloadView,
    SupervisorCourseSummaryListView,
    SupervisorCourseArchiveBatchDetailView,
    SupervisorCourseArchiveManageView,
    SupervisorCourseArchivesView,
    SupervisorCourseArchiveResultsView,
    SupervisorLandingView,
    SupervisorCourseSummaryView,
    SupervisorSubmissionFileDownloadView,
    SupervisorSubmissionDetailView,
    SupervisorTreeNodeCreateView,
    SupervisorTreeDataView,
    SupervisorTreeNodeDeleteView,
    SupervisorTreeNodeUpdateView,
    SupervisorContentUploadView,
    SupervisorContentBrowseView,
    SupervisorTreePageView,
    SupervisorExerciseSubmissionsView,
    TutorialDetailView,
)

urlpatterns = [
    path("", CourseListView.as_view(), name="home"),
    path("courses/<int:pk>/", CourseDetailView.as_view(), name="course_detail"),
    path("tutorials/<int:pk>/", TutorialDetailView.as_view(), name="tutorial_detail"),
    path("exercises/<int:pk>/", ExerciseDetailView.as_view(), name="exercise_detail"),
    path(
        "supervisor/exercises/<int:exercise_id>/submissions/",
        SupervisorExerciseSubmissionsView.as_view(),
        name="supervisor_exercise_submissions",
    ),
    path(
        "supervisor/submissions/<int:result_id>/",
        SupervisorSubmissionDetailView.as_view(),
        name="supervisor_submission_detail",
    ),
    path(
        "supervisor/submissions/<int:result_id>/file/",
        SupervisorSubmissionFileDownloadView.as_view(),
        name="supervisor_submission_file_download",
    ),
    path(
        "supervisor/archived-submissions/<int:result_id>/file/",
        SupervisorArchivedSubmissionFileDownloadView.as_view(),
        name="supervisor_archived_submission_file_download",
    ),
    path(
        "supervisor/courses/<int:course_id>/summary/",
        SupervisorCourseSummaryView.as_view(),
        name="supervisor_course_summary",
    ),
    path(
        "supervisor/courses/<int:course_id>/archives/manage/",
        SupervisorCourseArchiveManageView.as_view(),
        name="supervisor_course_archive_manage",
    ),
    path(
        "supervisor/courses/summary",
        SupervisorCourseSummaryListView.as_view(),
        name="supervisor_course_summary_list",
    ),
    path(
        "supervisor/courses/<int:course_id>/archive-results/",
        SupervisorCourseArchiveResultsView.as_view(),
        name="supervisor_course_archive_results",
    ),
    path(
        "supervisor/courses/<int:course_id>/archives/",
        SupervisorCourseArchivesView.as_view(),
        name="supervisor_course_archives",
    ),
    path(
        "supervisor/archives/<int:archive_batch_id>/",
        SupervisorCourseArchiveBatchDetailView.as_view(),
        name="supervisor_course_archive_batch_detail",
    ),
    path(
        "supervisor",
        SupervisorLandingView.as_view(),
        name="supervisor_landing",
    ),
    path(
        "supervisor/tree/",
        SupervisorTreePageView.as_view(),
        name="supervisor_tree",
    ),
    path(
        "supervisor/tree/data/",
        SupervisorTreeDataView.as_view(),
        name="supervisor_tree_data",
    ),
    path(
        "supervisor/tree/<str:node_type>/<int:node_id>/update/",
        SupervisorTreeNodeUpdateView.as_view(),
        name="supervisor_tree_node_update",
    ),
    path(
        "supervisor/tree/create/",
        SupervisorTreeNodeCreateView.as_view(),
        name="supervisor_tree_node_create",
    ),
    path(
        "supervisor/tree/<str:node_type>/<int:node_id>/delete/",
        SupervisorTreeNodeDeleteView.as_view(),
        name="supervisor_tree_node_delete",
    ),
    path(
        "supervisor/content/upload/",
        SupervisorContentUploadView.as_view(),
        name="supervisor_content_upload",
    ),
    path(
        "supervisor/content/browse/",
        SupervisorContentBrowseView.as_view(),
        name="supervisor_content_browse",
    ),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", RoleAwareLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]
